spring:
  application:
    name: library-management-system
  security:
    user:
      name: ahmed
      password: ${SECURITY_PASSWORD}
  datasource:
    url: jdbc:mysql://localhost:3306/book_system
    username: ${DB_USER}
    password: ${DB_PASSWORD}

springdoc:
  swagger-ui:
    path: /docs